### ISSUE TITLE
Problem with templatetag not setting the result variable in Django 2.1.7

### ISSUE THREAD

**Issue by rstorey** [cfpb/django-flags#28]
Thank you for this wonderfully documented app.

I'm using Django 2.1.7 and I have a flag defined named `SOCIAL_SHARE`.

If I use the template tag like this to try to detect the flag value in the template:
```
{% load feature_flags %}
{% flag_enabled 'SOCIAL_SHARE' as social_share_flag %}
```
Then when I use `social_share_flag` in an if statement later on, I get the following error:
```
[2019-03-06T14:52:50 DEBUG django.template:872] Exception while resolving variable 'social_share_flag' in template 'transcriptions/asset_detail.html'.
Traceback (most recent call last):
  File "/Users/rstorey/.virtualenvs/concordia-bbRAdEUp/lib/python3.6/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "/Users/rstorey/.virtualenvs/concordia-bbRAdEUp/lib/python3.6/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'social_share_flag'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rstorey/.virtualenvs/concordia-bbRAdEUp/lib/python3.6/site-packages/django/template/base.py", line 835, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'social_share_flag'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rstorey/.virtualenvs/concordia-bbRAdEUp/lib/python3.6/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'social_share_flag'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rstorey/.virtualenvs/concordia-bbRAdEUp/lib/python3.6/site-packages/django/template/base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [social_share_flag] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: 'V921fSmt5UYPpkfHohKUGyXUy0D7ftKE6e6BAmiZ2uhGYXyJPPqmg5g8C7YvY2vT'>, 'debug': True, 'sql_queries': <function debug.<locals>.<lambda> at 0x106bca950>, 'request': <WSGIRequest: GET '/campaigns/mary-church-terrell-advocate-for-african-americans-and-women/letters-between-friends-allies-and-others/mss425490081/mss425490081-1/?enable_social_share=False'>, 'user': <SimpleLazyObject: <User: rstorey>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x106bcb2b0>, 'messages': <django.contrib.messages.storage.session.SessionStorage object at 0x10688d978>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'MEDIA_URL': '/media/', 'SENTRY_FRONTEND_DSN': '', 'CONCORDIA_ENVIRONMENT': 'development', 'S3_BUCKET_NAME': None, 'APPLICATION_VERSION': '0.4.23.dev52+gfc7633f.d20190306', 'RAVEN_CONFIG': {'dsn': '', 'environment': 'development', 'release': 'fc7633f35105dffe6549e6969581957a39e7e510'}, 'VIEW_NAME': 'transcriptions:asset-detail', 'VIEW_NAME_FOR_CSS': 'transcriptions--asset-detail', 'PATH_LEVEL_1': 'campaigns', 'PATH_LEVEL_2': 'mary-church-terrell-advocate-for-african-americans-and-women', 'PATH_LEVEL_3': 'letters-between-friends-allies-and-others', 'PATH_LEVEL_4': 'mss425490081', 'PATH_LEVEL_5': 'mss425490081-1'}, {}, {'object': <Asset: mss425490081-1>, 'asset': <Asset: mss425490081-1>, 'view': <concordia.views.AssetDetailView object at 0x10689f320>, 'item': <Item: mss425490081: Mary Church Terrell Papers: Correspondence, 1886-1954; 1929, Jan.-Feb.>, 'project': <Project: Letters between friends, allies, and others>, 'campaign': <Campaign: Mary Church Terrell: Advocate for African Americans and Women>, 'transcription': None, 'next_open_asset_url': '/campaigns/mary-church-terrell-advocate-for-african-americans-and-women/next-transcribable-asset/?project=letters-between-friends-allies-and-others&item=mss425490081&asset=18817', 'next_review_asset_url': '/campaigns/mary-church-terrell-advocate-for-african-americans-and-women/next-reviewable-asset/?project=letters-between-friends-allies-and-others&item=mss425490081&asset=18817', 'transcription_status': 'not_started', 'next_asset_url': '/campaigns/mary-church-terrell-advocate-for-african-americans-and-women/letters-between-friends-allies-and-others/mss425490081/mss425490081-2/', 'asset_navigation': <QuerySet [(1, 'mss425490081-1'), (2, 'mss425490081-2'), (3, 'mss425490081-3'), (4, 'mss425490081-4'), (5, 'mss425490081-5'), (6, 'mss425490081-6'), (7, 'mss425490081-7'), (8, 'mss425490081-8'), (9, 'mss425490081-9'), (10, 'mss425490081-10'), (11, 'mss425490081-11'), (12, 'mss425490081-12'), (13, 'mss425490081-13'), (14, 'mss425490081-14'), (15, 'mss425490081-15'), (16, 'mss425490081-16'), (17, 'mss425490081-17'), (18, 'mss425490081-18'), (19, 'mss425490081-19'), (20, 'mss425490081-20'), '...(remaining elements truncated)...']>, 'current_asset_url': 'http://localhost:8000/campaigns/mary-church-terrell-advocate-for-african-americans-and-women/letters-between-friends-allies-and-others/mss425490081/mss425490081-1/?enable_social_share=False', 'tweet_text': '#ByThePeople @Crowd_LOC Mary Church Terrell Papers: Correspondence, 1886-1954; 1929, Jan.-Feb. http://localhost:8000/campaigns/mary-church-terrell-advocate-for-african-americans-and-women/letters-between-friends-allies-and-others/mss425490081/mss425490081-1/?enable_social_share=False', 'share_url': 'http://localhost:8000/campaigns/mary-church-terrell-advocate-for-african-americans-and-women/letters-between-friends-allies-and-others/mss425490081/mss425490081-1/?enable_social_share=False', 'tags': []}, {'block': <Block Node: site-main. Contents: [<TextNode: '\n        <main class="'>, <Block Node: extra_main_classes. Contents: []>, <TextNode: ' d-print-block">\n        '>, <Block Node: breadcrumbs-container. Contents: [<TextNode: '\n                <nav ari'>, <Block Node: breadcrumbs. Contents: []>, <TextNode: '\n                    </ol'>]>, <TextNode: '\n\n            '>, <Block Node: messages-container. Contents: [<TextNode: '\n                <div id='>, <django.template.defaulttags.CommentNode object at 0x106c21cf8>, <TextNode: '\n                        '>]>, <TextNode: '\n\n            '>, <Block Node: main_content. Contents: []>, <TextNode: '\n        </main>\n    '>]>}, {'block': <Block Node: main_content. Contents: [<TextNode: '\n<div id="contribute-main'>, <ForNode: for sequence, slug in asset_navigation, tail_len: 7>, <TextNode: '\n                        '>, <IfNode>, <TextNode: '" '>, <IfNode>, <TextNode: '>\n                       '>, <IfNode>, <TextNode: '" '>, <IfNode>, <TextNode: '>\n                       '>, <IfNode>, <TextNode: '\n\n                    Vie'>, <Variable Node: social_share_flag>, <TextNode: '\n\n            '>, <IfNode>, <TextNode: '\n\n            <div class='>, <Variable Node: next_open_asset_url>, <TextNode: '">Find a new page &rarr;<'>, <IfNode>, <TextNode: '>\n                       '>, <IfNode>, <TextNode: '>\n                       '>, <IfNode>, <TextNode: '>\n                       '>, <IfNode>, <TextNode: '>\n                       '>, <django.template.defaulttags.URLNode object at 0x106bb45f8>, <TextNode: '" data-transcription-stat'>, <Variable Node: transcription_status>, <TextNode: '" '>, <IfNode>, <TextNode: '>\n                    '>, <django.template.defaulttags.CsrfTokenNode object at 0x106bb4940>, <TextNode: '\n                    <inp'>, <Variable Node: transcription.pk|default:''>, <TextNode: '" />\n\n                   '>, <IfNode>, <TextNode: '\n                    </h2'>, <django.template.defaulttags.SpacelessNode object at 0x106ba00b8>, <TextNode: '\n                </form>\n'>, <django.template.defaulttags.URLNode object at 0x106b9ccf8>, <TextNode: '">\n                    '>, <django.template.defaulttags.CsrfTokenNode object at 0x106b9cfd0>, <TextNode: '\n\n                    <h2'>, <IfNode>, <TextNode: '\n                    </di'>, <ForNode: for tag in tags, tail_len: 5>, <TextNode: '\n                    </ul'>, <django.template.defaulttags.URLNode object at 0x106ba0710>, <TextNode: '">\n            Questions?'>, <django.template.defaulttags.URLNode object at 0x106bbe588>, <TextNode: '">Help Center</a>\n       '>, <Variable Node: next_open_asset_url>, <TextNode: '">\n                      '>, <Variable Node: next_review_asset_url>, <TextNode: '">\n                      '>, <Variable Node: next_open_asset_url>, <TextNode: '">\n                      '>, <Variable Node: next_review_asset_url>, <TextNode: '">\n                      '>, <Variable Node: next_open_asset_url>, <TextNode: '">\n                      '>, <django.template.defaulttags.URLNode object at 0x106bbeb70>, <TextNode: '" class="modal-dialog mod'>, <django.template.library.SimpleNode object at 0x106bbeb38>, <TextNode: '"></div>\n'>]>}]
```

However if I check the flag and set a variable reflecting flag status in the view, it works fine (abbreviated):

```
from flags.state import flag_enabled

@method_decorator(never_cache, name="dispatch")
class AssetDetailView(DetailView):
 
    def get_context_data(self, **kwargs):

        ctx["social_share_flag"] = flag_enabled("SOCIAL_SHARE", request=self.request)
        return ctx
```

Am I doing something wrong with the templatetag, or is something broken?

**Comment by willbarton** [comment]
@rstorey I'm not sure right off why that wouldn't work — that's certainly the way the template tag is meant to be used.

Looking at the last line of the traceback, it does look like you have a `<Variable Node: social_share_flag>` in your `main_content` block... could it be that the variable was defined in that block and the if statement was outside of it?

**Comment by rstorey** [comment]
Yep - user error. The variable has to be defined in the same block that uses it.
